#docker network create --driver bridge --subnet=172.30.10.0/24 wp-net

version: "3.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    domainname: master.net
    hostname: master
    #network_mode: wp-net
    networks:
        web-net:
           ipv4_address: 172.30.10.2
    dns:
     - 127.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: '2547561'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
       - '/mnt/PKG/Docker/Volume/Pi-Hole/etc/pihole/:/etc/pihole/'
       - '/mnt/PKG/Docker/Volume/Pi-Hole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
      #- './etc-pihole/:/etc/pihole/'
      #- './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
   web-net:
     external: true

